apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mc2-crudtest.fullname" . }}-ingress
  labels:
    app: {{ include "mc2-crudtest.name" . }}
  annotations:
    # Adjust or add annotations according to your Ingress controller.
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mc2-crudtest.fullname" . }}-web
                port:
                  number: {{ .Values.service.port }}
