apiVersion: v1
kind: Service
metadata:
  name: {{ include "mc2-crudtest.fullname" . }}-web
  labels:
    app: {{ include "mc2-crudtest.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "mc2-crudtest.name" . }}
    component: web
