apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mc2-crudtest.fullname" . }}-sql
type: Opaque
data:
  # Base64 encode your SA password. For example, "Your_password123" encoded in base64:
  saPassword: {{ .Values.sql.saPassword | b64enc }}
