apiVersion: v1
kind: Service
metadata:
  name: {{ include "mc2-crudtest.fullname" . }}-sql
  labels:
    app: {{ include "mc2-crudtest.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
      name: mssql
  selector:
    app: {{ include "mc2-crudtest.name" . }}
    component: sql
